name: run

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '10 16 * * *'

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - run: npm ci

      - run: npm run main
        env:
          GLADOS: ${{ secrets.GLADOS }}
          NOTIFY: ${{ secrets.NOTIFY }}
